import React, { Component } from 'react'


export class NetworkLeft extends Component {
  render() {
    return (
      <React.Fragment>
        <p>THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL
        THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL
        THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL
        THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL
        THIS IS NETWORK'S LEFT PANEL THIS IS NETWORK'S LEFT PANEL
        </p>
      </React.Fragment>
    )
  }
}

export default NetworkLeft
